### ISSUE TITLE
Switch from sphinx to MkDocs

### ISSUE THREAD

**Issue by jernejfrank** [DAGWorks-Inc/hamilton#1170]
**Is your feature request related to a problem? Please describe.**
Documenting code in RST is tedious, setting up sphinx is another hurdle to overcome for contributions and you need to re-render it every time you want to see changes.

**Describe the solution you'd like**
Switching to MkDocs: https://www.mkdocs.org/user-guide/writing-your-docs/

For one-sided comparison to Sphinx: https://dev.to/coderatul/simplify-your-documentation-workflow-with-mkdocs-a-markdown-based-alternative-to-sphinx-365j#:~:text=Sphinx%20and%20MkDocs%20are%20two,easier%20to%20use%20than%20Sphinx.

**Describe alternatives you've considered**
Leave it as is.

I am fully prepared for this to be shut down, but still worth a try.

**Comment by elijahbenizzy** [comment]
Context:
1. @jernejfrank and I were complainng about RST, it's absolute junk
2. LOL, we switched over two years ago IIRC
3. Intermediate world is [(https://www.sphinx-doc.org/en/master/usage/markdown.html) lets us write in markdown...

**Comment by zilto** [comment]
For context, I've previously mentioned my issues with Sphinx several times before. I don't see many benefits to `.rst`, but the feedback I got was that Sphinx was relevant for `Reference` sections. Also, we already use the [myst parser](https://myst-nb.readthedocs.io/en/latest/) extension and several pages of the documentation are already in `.md` ([see here](https://github.com/DAGWorks-Inc/hamilton/tree/main/docs/integrations))

I would suggest considering migrating to `Docusaurus` instead of Mkdocs especially since we have the [dataflow hub](https://hub.dagworks.io/) already on docusaurus and have familiarity with the toolset

Pain points / notes:
- sphinx autoreload is extra slow (parses everything) whereas docusaurus is faster
- to use Sphinx in `Reference`, we need to format code snippets in docstrings using `rst`. However, VSCode, the most popular IDE, displays docstring as `markdown`
- Docusaurus would allow to unify the DAGWorks website, dataflow hub, and leave room custom JS pages
- we need to estimate migration efforts

**Comment by zilto** [comment]
Will close as switching to MKDocs isn't currently planned. We can revisit later
