### ISSUE TITLE
Can't have a function with both Parallelizable and Collect

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#652]
There are two things:

1. it doesn't work
2. the graph visualization doesn't handle this case

# Current behavior
The following fails:

```python
# functions.py
# functions.py - declare and link your transformations as functions....
import pandas as pd
from hamilton.htypes import Parallelizable, Collect


def motor(motor_list: list[int]) -> Parallelizable[int]:
   for _motor in motor_list:
      yield _motor

def _is_motor_on(motor: int ) -> bool:
    return motor % 2 == 0

def motor_status(motor: int) -> dict:
   # logic to check
   return {
   "motor_id": motor,
   "is_on": _is_motor_on(motor)
  }

def aggregate_statuses(motor_status: Collect[dict]) -> list[dict]:
    return list(motor_status)

def on_motor(motor_status: Collect[dict]) -> Parallelizable[int]:
  for motor_dict in motor_status:
      if motor_dict["is_on"]:
          yield motor_dict["motor_id"]

def status_check_1(on_motor: int) -> float:
    # some status check.
    return 2.3 * on_motor

def status_check_2(on_motor: int, status_check_1: float) -> str:
    return f"some result based on {on_motor} and {status_check_1}"

def status_result(on_motor: int, status_check_1: float, status_check_2: str) -> dict:
    return locals()

def on_motor_statuses(status_result: Collect[dict]) -> pd.DataFrame:
    return pd.DataFrame(status_result)
```

```python
# run.py
# And run them!
import functions
from hamilton import base
from hamilton import driver
from hamilton.execution import executors

dr = (
    driver.Builder()
    .enable_dynamic_execution(allow_experimental_mode=True)
    .with_modules(functions)
    # .with_remote_executor(executors.SynchronousLocalTaskExecutor())
    .with_adapters(base.PandasDataFrameResult())
    .build()
)
# dr = driver.Driver({}, functions)
result = dr.execute(
  ['on_motor_statuses'],
  inputs={'motor_list': [1, 2, 3, 4, 5]}
)
print(result)
dr.display_all_functions(
   "graph.dot", orient="TB", show_legend=False)
```

## Stack Traces
```python
  File "hamilton/hamilton/driver.py", line 650, in raw_execute
    results = self.graph_executor.execute(
  File "hamilton/hamilton/driver.py", line 230, in execute
    raw_result = results_cache.read(final_vars)
  File "hamilton/hamilton/execution/state.py", line 113, in read
    raise KeyError(f"Key {formatted_key} not found in cache")  # noqa E713
KeyError: 'Key on_motor_statuses not found in cache'
```

## DAG image
![graph dot](https://github.com/DAGWorks-Inc/hamilton/assets/2328071/c448e3ce-f4e9-49b8-9a68-162d5b6c362d)

## Steps to replicate behavior
See code above

## Library & System Information
Latest.

# Expected behavior
I don't see why this couldn't work.

# Additional context
If you make `on_motor` depend on `aggregate_statuses`  and thus have a node in between, things work.

**Comment by zilto** [comment]
Would like to hear from @elijahbenizzy, but I think this dataflow works as intended since Parallelizable/Collect was introduced. 

## Issue 1: `motor` is collected twice
Parallel/Collect work in pair. Since `motor` is Parallel, it should be Collected downstream only once. In the simplest case, Parallel iterates and Collect creates a list. When I see a `Parallel` when reading the code, I'm asking myself "where is it collected?". It seems to improve readability to have only collected once.

## Issue 2: a node can't be collect and parallel
I don't know why it's a limitation, but it seems to improve readability of the graph. [Metaflow ](https://docs.metaflow.org/metaflow/basics#foreach) imposes the same constraint. Each `foreach` step need an explicit `join` step to merge artifacts (it's not always trivial). However, Metaflow allows for nested `foreach`.

## Solution
As you describe @skrawcz , the following code works and is also IMHO more readable.

```python
def motor(motor_list: list[int]) -> Parallelizable[int]:
   for _motor in motor_list:
      yield _motor

def _is_motor_on(motor: int ) -> bool:
    return motor % 2 == 0

def motor_status(motor: int) -> dict:
   # logic to check
   return {
   "motor_id": motor,
   "is_on": _is_motor_on(motor)
  }

def motor_status_collection(motor_status: Collect[dict]) -> list[dict]:
    return list(motor_status)

def on_motor(motor_status_collection: list[dict]) -> Parallelizable[int]:
  for motor_dict in motor_status_collection:
      if motor_dict["is_on"]:
          yield motor_dict["motor_id"]

def status_check_1(on_motor: int) -> float:
    # some status check.
    return 2.3 * on_motor

def status_check_2(on_motor: int, status_check_1: float) -> str:
    return f"some result based on {on_motor} and {status_check_1}"

def status_result(on_motor: int, status_check_1: float, status_check_2: str) -> dict:
    return locals()

def on_motor_statuses(status_result: Collect[dict]) -> pd.DataFrame:
    return pd.DataFrame(status_result)

```

![image](https://github.com/DAGWorks-Inc/hamilton/assets/68975210/5ebed4b9-29b5-4308-b7e0-cac202c02380)


## Next steps
It seems that the desired user workflow is easy to support with the current features (with the few edits shared). I think we can improve the documentation around Parallel/Collect. Also, we might want to catch these errors at Driver instantiation and make the graph fail. I believe the challenge is that without the parallel / collect stuff, the initial DAG structure is valid. Otherwise, since the submitted DAG is invalid, it's unclear what the behavior of the viz should be. The issue seem to exist upstream of the viz.
